language: python
python:
- 3.6.5
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run python manage.py test -v 2
deploy:
  provider: heroku
  api_key:
    secure: aXncPuajGKH9aTDyWQ5B9Wvw0aY8plQz/TPTaGXcPpcyBqnprE8A2Td3jK0o4xTmhFh1DYFrSyNCWG9WzdWCuZ7AfG+vyoI8NSwnYMPZV+rAgQ3CMr5XuhCv8CP2ByoDtsW2LyUtbVMMonfj4Y/ysWuhOy35WEFCSjcdCNfqFI+yfoRJw1K7+JAiAwy1J/F6/X1O0OxoveECvb96i/2b9vxxg9CZlLQlFeFn91XJpx5BVQUzrb64rItK6SZaaijxBleeOMtTABoIddwsmS+MWV5E0JT1/kA0C0sbqW+uu2M048W/ZO6u3wBlWuLt6p14oDb0092KDSKOlTHg6oklf8KW+/Ehvfsud/qLArxpBpubFR0IwT4Zm3YtF4NCKkmoZjMifHkFV3tkY49QEkiTaPPKrU4HU3vFH/5LaFfbWTuSi6ZuvyBTl7+CKF86zUCpSi3595VjOnvyQFJ9bGhlyrJp+ww5E6dG4ANrJ38XrzkmrZvpNGv3cw6+Y+C8Nw0tRfUPWF8Wr3DodBJ2+BJJFBlSTTu2jTfL7zy0OO1kCgXse2XarNrRZQ0MtDlG6XcNDXhBCuk0Hb8nd1LxgtFbV+JGVUYCCedkH2aCUl5FeuiaalRGnjb7G16oFlKwcMuLQMqi3xHH7x3PiAT+K4ISolKeCeknjcZMG+UIrRd9KMg=
  app: pacific-wildwood-68828
  on:
    repo: varian97/a1-violet
