language: python
python:
- 3.6.5
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run python manage.py test -v 2
deploy:
  provider: heroku
  api_key:
    secure: mn9FhO8TORZx1MXDmlBUHgFByRhCAxmZWw9qxuouVDbAv5LzJF8I6sBsDdDg7q1CVkJ0tFToei1hqe5xPaaPsSgkHVvcr/9bW7t8832mr1yLRhlGNKzCaerw9rK3qUohDlEoxxuYgeQYkzNd19zPjTqtFLLgDmnhyKnstD1SR3b3Ua8wN+pJf6CoT4xXveOvix9l8UXewYw6VBoU+TLuuDaOZD+30cA5lpW22SKOd+z6lkuD3/VIbs9+MFKo0LJDEVB/ZVJFyGF7k2HIClQBoYSvdTr4/HecaXwOWxuYC0WUEgx9htJGNcY0SX0KVdorkFB3UAtIgLjQkxIFx4gayHoyQXf2zwQDT8+S2+VzKRZoJg9ipizKexe/YOZIlSBK/4oDtr9CAtVviwYyEszibmG7vakjfQGIQb1tzgFQLmZzeZHLCDkFoyK02uEsNl5CHd54WmpgqlfPHL5+kP0vSq8ns+pNonvrrXk+c/9dOVCvjxi2UFGk5bDFB76bdCFY61wYv7eqh3XWWRCq+1HF5tn3hnHnbRuEjRFWdXEH4QgZFLGfhvTNwaqB0B/mtWmXN8yASP7IKjnz8MrmCsez4f8r49lSAd+cV/84gv8AAyOk/yWzh3hkt0YFHP+o8YVw+CGXsWbrUlqRfA0c5GyO3t7RF1wIWfrKHg2wKJOov+k=
  app: pacific-wildwood-68828
  on:
    repo: varian97/a1-violet
